# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images (SVG Only)

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Make assets dir
        run: mkdir -p assets
        
      # إعداد متغيرات البيئة لكسر الكاش
      - name: Setup Cache Bust
        run: |
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
          
      # -----------------------------------------------
      # 1. بطاقة إحصاءات المستخدم
      # -----------------------------------------------
      - name: Download GitHub Stats image
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }} # تمرير التوكن مباشرة
        run: |
          curl -sS -f "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=transparent&count_private=true&access_token=${GH_TOKEN}&line_height=30&card_width=500&cache_bust=${TIMESTAMP}" -o assets/github-stats.svg

      # -----------------------------------------------
      # 2. بطاقة اللغات (إلغاء التصفية القسري وإظهار 20 لغة)
      # -----------------------------------------------
      - name: Download Top Languages (Disable Filtering)
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }} # تمرير التوكن مباشرة
        run: |
          # هذه المعلمة تجبر الخدمة على عدم تجاهل أي لغة صغيرة (أقل من 1%)
          # هذا هو الحل الأكيد لظهور JavaScript ذات النسبة الصغيرة.
          curl -sS -f "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&theme=transparent&langs_count=20&count_private=true&access_token=${GH_TOKEN}&cache_bust=${TIMESTAMP}&disable_automatic_language_detection=true" -o assets/top-langs.svg

      # -----------------------------------------------
      # 3. بطاقة Streak
      # -----------------------------------------------
      - name: Download Streak
        run: |
          curl -sS -f "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=transparent" -o assets/streak.svg

      # -----------------------------------------------
      # 4. Commit and Push
      # -----------------------------------------------
      - name: Commit and push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add assets/*.svg
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats SVGs [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
