# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images (Final)

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Make assets dir
        run: mkdir -p assets
        
      # إعداد متغيرات البيئة لكسر الكاش (لضمان تحديث الصور)
      - name: Setup Env
        run: |
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
        
      # -----------------------------------------------
      # 1. بطاقة إحصاءات المستخدم (هذه تعمل مع البيانات الخاصة)
      # -----------------------------------------------
      - name: Download GitHub Stats image (Includes Private Data)
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # count_private=true يعمل بشكل موثوق لبطاقة الإحصاءات العامة
          curl -sS -f "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=dark&count_private=true&access_token=${GH_TOKEN}&cache_bust=${TIMESTAMP}" -o assets/github-stats.svg

      # -----------------------------------------------
      # 2. بطاقة اللغات (ستحاول، ولكن قد تفشل بسبب قيود الخدمة)
      # -----------------------------------------------
      - name: Download Top Languages (Limited by Service Host)
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # نطلب 15 لغة، لكن الخدمة قد تتجاهل البيانات الخاصة.
          curl -sS -f "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&theme=dark&count_private=true&access_token=${GH_TOKEN}&langs_count=15&cache_bust=${TIMESTAMP}" -o assets/top-langs.svg

      # -----------------------------------------------
      # 3. بطاقة Streak
      # -----------------------------------------------
      - name: Download Streak
        run: |
          curl -sS -f "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=dark" -o assets/streak.svg

      # -----------------------------------------------
      # 4. Commit and Push
      # -----------------------------------------------
      - name: Commit and push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add assets/*.svg
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats SVGs [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
