# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images (SVG Only)

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Make assets dir
        run: mkdir -p assets
        
      # إعداد متغيرات البيئة لكسر الكاش
      - name: Setup Cache Bust
        run: |
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      # -----------------------------------------------
      # 0. تم إزالة اختبار الوصول (لأنه ناجح - Status 200)
      # -----------------------------------------------

      # -----------------------------------------------
      # 1. بطاقة إحصاءات المستخدم
      # -----------------------------------------------
      - name: Download GitHub Stats image
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # نستخدم theme=dark لضمان التباين
          curl -sS -f "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=dark&count_private=true&access_token=${GH_TOKEN}&line_height=30&card_width=500&cache_bust=${TIMESTAMP}" -o assets/github-stats.svg

      # -----------------------------------------------
      # 2. بطاقة اللغات (استبعاد المنتج المسيطر لفرض ظهور JavaScript)
      # -----------------------------------------------
      - name: Download Top Languages (Exclude productspy)
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # هذا السطر يستبعد المستودع الذي يسيطر على الإحصاءات
          EXCLUDE_REPO_NAME="productspy"
          
          # نستخدم langs_list لفرض ظهور هذه اللغات ونطلب 7 لغات كحد أقصى
          LANGS_LIST="Python,JavaScript,HTML,CSS,Shell,TypeScript,Vue"
          
          curl -sS -f "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&theme=dark&count_private=true&access_token=${GH_TOKEN}&cache_bust=${TIMESTAMP}&langs_count=7&langs_list=${LANGS_LIST}&exclude_repo=${EXCLUDE_REPO_NAME}" -o assets/top-langs.svg

      # -----------------------------------------------
      # 3. بطاقة Streak
      # -----------------------------------------------
      - name: Download Streak
        run: |
          curl -sS -f "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=dark" -o assets/streak.svg

      # -----------------------------------------------
      # 4. Commit and Push
      # -----------------------------------------------
      - name: Commit and push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add assets/*.svg
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats SVGs [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
