# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images (SVG Only)

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Make assets dir
        run: mkdir -p assets
      
      # إعداد متغيرات البيئة للتوكن
      - name: Setup Token Env
        run: |
          echo "GH_TOKEN=${{ secrets.GH_STATS_TOKEN }}" >> $GITHUB_ENV
          
      # -----------------------------------------------
      # 1. بطاقة إحصاءات المستخدم (Theme: vue) - يتم حفظها كـ SVG
      # -----------------------------------------------
      - name: Download GitHub Stats image
        run: |
          curl -sS "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=vue&count_private=true&access_token=${GH_TOKEN}&line_height=30&card_width=500" -o assets/github-stats.svg

      # -----------------------------------------------
      # 2. بطاقة اللغات (Theme: vue) - يتم حفظها كـ SVG
      # -----------------------------------------------
      - name: Download Top Languages
        run: |
          curl -sS "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&theme=vue&langs_count=10&count_private=true&access_token=${GH_TOKEN}" -o assets/top-langs.svg

      # -----------------------------------------------
      # 3. بطاقة Streak (Theme: vue) - يتم حفظها كـ SVG
      # -----------------------------------------------
      - name: Download Streak
        run: |
          curl -sS "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=vue" -o assets/streak.svg

      # -----------------------------------------------
      # 4. Commit and Push (Commiting .svg files)
      # -----------------------------------------------
      - name: Commit and push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # **قم بإضافة ملفات SVG بدلاً من PNG**
          git add assets/*.svg
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats SVGs [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
