# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # هذا السطر ليس ضرورياً لتحديث الريبو نفسه، لكن لا ضرر فيه
          fetch-depth: 0
          
      - name: Make assets dir
        # إذا لم يكن المجلد موجوداً، يتم إنشاؤه
        run: mkdir -p assets

      - name: Download GitHub Stats image
        # يفضل وضع الـ token في متغيرات البيئة بدلاً من وضعه في الـ URL مباشرة (لأغراض الأمان)
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -sS "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=radical&count_private=true&access_token=${GH_TOKEN}" -o assets/github-stats.svg

      - name: Download Top Languages
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -sS "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&layout=compact&theme=radical&langs_count=10&count_private=true&access_token=${GH_TOKEN}" -o assets/top-langs.svg

      - name: Download Streak
        run: |
          # هذا الرابط لا يحتاج إلى token
          curl -sS "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=radical" -o assets/streak.svg

      - name: Install SVG Conversion Tools
        # تجميع عملية التثبيت في خطوة منفصلة لزيادة وضوح سير العمل
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin

      - name: Convert SVG to PNG
        # تجميع أوامر التحويل في خطوة واحدة
        run: |
          rsvg-convert assets/github-stats.svg -o assets/github-stats.png
          rsvg-convert assets/top-langs.svg -o assets/top-langs.png
          rsvg-convert assets/streak.svg -o assets/streak.png
          
      # --- هذه هي الخطوة المصححة ---
      - name: Commit and push images
        # استخدام GITHUB_TOKEN المدمج يكفي ولا يحتاج للتعريف في 'env'
        run: |
          # إعداد معلومات المستخدم للـ commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # إضافة ملفات PNG فقط
          git add assets/*.png
          
          # التحقق مما إذا كانت هناك تغييرات ليتم التزامها (Commit)
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats images [skip ci]"
            # استخدام الطريقة الموصى بها للدفع (push) عبر GITHUB_TOKEN
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
          # **لقد قمت بإضافة fi هنا لإنهاء العبارة الشرطية**
