# Workflow: تحديث صور إحصاءات GitHub تلقائياً
name: Update GitHub Stats Images

# إعطاء صلاحية الكتابة للملفات (مهم لعملية الـ commit)
permissions:
  contents: write

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:
    - cron: '0 */6 * * *' # كل 6 ساعات

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Make assets dir
        run: mkdir -p assets

      # -----------------------------------------------
      # 1. بطاقة إحصاءات المستخدم (Theme, Colors, Size)
      # تم تغيير الثيم إلى 'dracula' وتم زيادة حجم البطاقة لضمان ظهور كل الإحصاءات.
      # ملاحظة: تم إبقاء hide=stars لإخفاء النجوم (إذا أردت رؤيتها، احذف &hide=stars).
      # -----------------------------------------------
      - name: Download GitHub Stats image
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -sS "https://github-readme-stats.vercel.app/api?username=renqwee&show_icons=true&hide=stars&theme=dracula&count_private=true&access_token=${GH_TOKEN}&line_height=30&card_width=500" -o assets/github-stats.svg

      # -----------------------------------------------
      # 2. بطاقة اللغات (Colors & Layout Fix)
      # تم تغيير الثيم إلى 'dracula' وتم إزالة تنسيق 'compact' لمنع التداخل (Compact Layout).
      # -----------------------------------------------
      - name: Download Top Languages
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # تم إزالة layout=compact لمنع تداخل اللغات
          curl -sS "https://github-readme-stats.vercel.app/api/top-langs/?username=renqwee&theme=dracula&langs_count=10&count_private=true&access_token=${GH_TOKEN}" -o assets/top-langs.svg

      # -----------------------------------------------
      # 3. بطاقة Streak (Colors)
      # تم تغيير الثيم إلى 'dracula'.
      # -----------------------------------------------
      - name: Download Streak
        run: |
          curl -sS "https://github-readme-streak-stats.herokuapp.com/?user=renqwee&theme=dracula" -o assets/streak.svg

      - name: Install SVG Conversion Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin

      # -----------------------------------------------
      # 4. تحسين جودة الصور (High Quality Conversion)
      # استخدام -d 300 لرفع الدقة لضمان وضوح النص والألوان.
      # -----------------------------------------------
      - name: Convert SVG to PNG with high quality
        run: |
          rsvg-convert -d 300 -w 1200 assets/github-stats.svg -o assets/github-stats.png
          rsvg-convert -d 300 -w 800 assets/top-langs.svg -o assets/top-langs.png
          rsvg-convert -d 300 -w 800 assets/streak.svg -o assets/streak.png
          
      # -----------------------------------------------
      # 5. إصلاح خطأ Shell Commit (تمت إضافة fi)
      # -----------------------------------------------
      - name: Commit and push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add assets/*.png
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update GitHub stats images [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
